import { Quote } from 'lucide-react'

const testimonials = [
  { quote: 'Honestly, I’m really happy with the website Kushagra made for us. We wanted something simple, clean and professional that actually shows our rooms and gives people the basic information they need before booking. Kushagra understood what we were looking for and handled most of the work himself. He also made changes whenever we had feedback, which made the whole process quite easy for us. The website has given our guest house a much more professional presence online. I’m happy with how it turned out and would definitely recommend Kushagra if someone is looking to get a website made for their hotel or guest house.', by: 'Owner, Butola Guest House, Dehradun' },
  { quote: 'I’m really happy with the website Kushagra made for Hotel Ajanta. We wanted something that looked professional but was still simple and easy for our guests to use. Kushagra understood what we needed and was very patient with our changes and suggestions. He took care of everything from the design to the final website, and the overall process was quite smooth. The website has given our hotel a much better presence online. It looks clean, professional, and properly represents our hotel. I’m very satisfied with the work Kushagra has done for us.', by: 'Owner, Hotel Ajanta' },
  { quote: 'Before this, getting customers to leave a review was honestly quite difficult. Most guests would say they were happy with the service, but when it came to actually leaving a Google review, very few people would take the time to do it. Kushagra understood the problem and came up with a really simple solution. He developed an NFC-based review system where our customers can simply tap their phone and complete the review process in just a few steps. What I liked most was that he first understood the problem in our business and then built a system around it. It has made the whole review process much easier for our customers and our staff.', by: 'Hotel Owner' },
  { quote: 'Before working with Kushagra, most of our online presence was quite basic. We were getting patients through referrals, but we didn’t have a proper website where a new patient could quickly understand our services and contact us. Kushagra first understood how our clinic actually works and then built the website around that. He made it much easier for patients to find our treatments, see the clinic information and get in touch with us. What I liked was that he didn’t just focus on making the website look good. He also thought about how a patient would actually use it.', by: 'Owner, Dental Clinic' },
  { quote: 'We had property information scattered across WhatsApp, PDFs and different platforms, so explaining everything to a new client was taking a lot of time. Kushagra built a website that brought everything together in one place. The properties are easier to show, the information is organised properly, and clients can contact us directly. What I appreciated most was that he understood the sales process before designing the website. It wasn’t just a portfolio of properties—it was built around how we actually deal with customers.', by: 'Real Estate Business Owner' },
  { quote: 'Before working with Kushagra, we had a difficult time explaining what our yoga center actually offers through our online presence. We had good programs and a lot of experience, but our website didn’t communicate that properly. Kushagra took the time to understand our center, our approach to yoga, and the kind of people we wanted to reach. He then built the website around that instead of simply putting information on a few pages. The difference is quite noticeable. The website now feels much more like our center and makes it easier for someone discovering us for the first time to understand what we do.', by: 'Founder, Yoga & Wellness Center' },
]

function TestimonialCard({ quote, by }: typeof testimonials[number]) {
  return <article className="testimonial-card"><Quote size={20} /><p>“{quote}”</p><span>— {by}</span></article>
}

export default function Testimonials() {
  const columns = [testimonials.slice(0, 2), testimonials.slice(2, 4), testimonials.slice(4, 6)]
  return <section className="testimonials-section" id="testimonials"><div className="testimonials-heading"><div className="eyebrow"><span>Client voice</span><i /></div><h2>Good work should<br /><em>feel useful.</em></h2><p>Words from people who trusted me with a real business problem.</p></div><div className="testimonial-columns" aria-label="Client testimonials">{columns.map((column, columnIndex) => <div className={`testimonial-column testimonial-column-${columnIndex + 1}`} key={columnIndex}><div className="testimonial-track">{[...column, ...column].map((item, index) => <TestimonialCard {...item} key={`${item.by}-${index}`} />)}</div></div>)}</div></section>
}
